"use strict";
(()=>{
const CARNET_URL="https://carnetentrainementv2.vercel.app/",KEY="chronoCarnetEPS_v4",$=id=>document.getElementById(id);let raf=null,recoveryTimer=null;
const PERF_F=[[306,.25],[299,.5],[292,.75],[285,1],[278,1.25],[272,1.5],[266,1.75],[260,2],[254,2.25],[248,2.5],[242,2.75],[236,3],[230,3.25],[225,3.5],[220,3.75],[215,4],[210,4.25],[205,4.5],[200,4.75],[195,5],[190,5.25],[185,5.5],[180,5.75],[175,6]],PERF_M=[[242,.25],[237,.5],[232,.75],[227,1],[222,1.25],[217,1.5],[212,1.75],[207,2],[202,2.25],[197,2.5],[192,2.75],[188,3],[184,3.25],[180,3.5],[176,3.75],[172,4],[168,4.25],[165,4.5],[162,4.75],[159,5],[156,5.25],[153,5.5],[150,5.75],[147,6]];
const base=()=>({mode:"training",view:"setup",started:false,running:false,startedAt:0,accumulatedMs:0,totalDistance:1000,splitDistance:100,displayMode:"both",targetMs:null,runners:[],results:[],activeRace:1,recoveryStartedAt:null,teacherReveal:false});let state;try{state={...base(),...JSON.parse(localStorage.getItem(KEY)||"{}"),running:false,startedAt:0}}catch{state=base()}
const save=()=>localStorage.setItem(KEY,JSON.stringify({...state,running:false,startedAt:0})),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=ms=>{ms=Math.max(0,Math.round(ms||0));let cs=Math.floor(ms%1000/10),s=Math.floor(ms/1000)%60,m=Math.floor(ms/60000);return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}.${String(cs).padStart(2,"0")}`},short=ms=>`${(Math.abs(ms||0)/1000).toFixed(2)} s`,parse=v=>{if(!v)return null;let a=v.trim().replace(",",".").split(":").map(Number);if(a.some(Number.isNaN))return null;return(a.length===1?a[0]:a[0]*60+a[1])*1000},elapsed=()=>state.accumulatedMs+(state.running?performance.now()-state.startedAt:0),spd=(d,t)=>t?d/(t/1000)*3.6:0,signed=v=>v==null?"—":`${v>0?"+":v<0?"−":"±"}${short(v)}`,splits=()=>Math.floor(state.totalDistance/state.splitDistance),rr=(id,race=state.activeRace)=>state.results.filter(x=>x.runnerId===id&&x.race===race),done=(id,race=state.activeRace)=>rr(id,race).length>=splits();
function toast(s){$("toast").textContent=s;$("toast").hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").hidden=true,1800)}
function renderSetup(){document.querySelectorAll('[name="mode"]').forEach(x=>x.checked=x.value===state.mode);let c=state.mode!=="training";$("trainingConfig").classList.toggle("hidden",c);$("ccfConfig").classList.toggle("hidden",!c);document.querySelectorAll(".ccfRunnerField").forEach(x=>x.classList.toggle("hidden",!c));$("runnerSex").classList.toggle("hidden",!c);$("totalDistance").value=[200,400,600,800,1000,1200,1500,2000,3000].includes(state.totalDistance)?state.totalDistance:"custom";$("splitDistance").value=[50,100,150,200,250,400].includes(state.splitDistance)?state.splitDistance:"custom";$("customDistance").value=state.totalDistance;$("customSplit").value=state.splitDistance;$("displayMode").value=state.displayMode;$("targetTime").value=state.targetMs?fmt(state.targetMs):"";recap();runnerSetup()}
function readConfig(){if(state.mode!=="training"){state.totalDistance=800;state.splitDistance=200;state.displayMode="cumulative";return}let t=$("totalDistance").value,s=$("splitDistance").value;state.totalDistance=t==="custom"?+$("customDistance").value:+t;state.splitDistance=s==="custom"?+$("customSplit").value:+s;state.displayMode=$("displayMode").value;state.targetMs=parse($("targetTime").value);save();recap()}
function recap(){let ok=state.totalDistance>0&&state.splitDistance>0&&state.totalDistance%state.splitDistance===0;$("configMessage").textContent=ok?"":`Distance incompatible avec l’intermédiaire.`;$("configRecap").innerHTML=[state.mode==="training"?"Entraînement":state.mode==="simulation"?"Simulation CCF":"CCF / Examen",`${state.totalDistance} m`,`${state.splitDistance} m / passage`].map(x=>`<span>${x}</span>`).join("")}
function runnerSetup(){let b=$("runnerSetupList");b.innerHTML=state.runners.length?state.runners.map(r=>`<span class="runnerChip"><strong>${esc(r.name)}</strong>${state.mode!=="training"?` · ${r.sex}`:""}<button data-del="${r.id}">×</button></span>`).join(""):"Aucun coureur ajouté.";b.querySelectorAll("[data-del]").forEach(x=>x.onclick=()=>{state.runners=state.runners.filter(r=>r.id!==x.dataset.del);state.results=state.results.filter(r=>r.runnerId!==x.dataset.del);save();runnerSetup()})}
function addRunner(){let n=$("runnerName").value.trim();if(!n)return;state.runners.push({id:uid(),name:n,sex:$("runnerSex").value,project1Ms:parse($("project1").value),project2Ms:parse($("project2").value)});$("runnerName").value="";save();runnerSetup()}
function launch(){readConfig();if(!state.runners.length)return toast("Ajoute un coureur.");if(state.totalDistance%state.splitDistance)return toast("Configuration incohérente.");state.view="performance";state.activeRace=1;save();render()}
function renderTimer(){$("mainTime").textContent=fmt(elapsed());$("startBtn").textContent=state.running?"EN COURS":state.started?"REPRENDRE":"DÉPART";$("startBtn").disabled=state.running;$("pauseBtn").disabled=!state.running;let p=$("statusPill");p.className=`statusPill ${state.running?"running":state.started?"paused":"idle"}`;p.textContent=state.running?"En cours":state.started?"En pause":"Prêt"}
function tick(){renderTimer();raf=requestAnimationFrame(tick)}function start(){if(state.running)return;state.started=true;state.running=true;state.startedAt=performance.now();renderTimer()}function pause(){if(!state.running)return;state.accumulatedMs+=performance.now()-state.startedAt;state.running=false;state.startedAt=0;save();renderTimer()}function reset(){if(state.results.some(x=>x.race===state.activeRace)&&!confirm("Effacer les temps de cette course ?"))return;state.started=state.running=false;state.accumulatedMs=state.startedAt=0;state.results=state.results.filter(x=>x.race!==state.activeRace);save();renderPerf()}
function record(id){if(!state.started)return toast("Appuie d’abord sur DÉPART.");if(done(id))return;let r=state.runners.find(x=>x.id===id),a=rr(id),cum=elapsed(),prev=a.length?a.at(-1).cumulativeMs:0,lap=cum-prev,pass=a.length+1,dist=pass*state.splitDistance,delta=a.length?lap-a.at(-1).lapMs:null,target=state.mode==="training"?state.targetMs:(state.activeRace===1?r.project1Ms:r.project2Ms),targetDelta=target?cum-target*(dist/state.totalDistance):null;state.results.push({id:uid(),runnerId:id,runnerName:r.name,race:state.activeRace,passage:pass,distance:dist,cumulativeMs:cum,lapMs:lap,speed:spd(state.splitDistance,lap),deltaMs:delta,targetDelta});if(navigator.vibrate)navigator.vibrate(25);save();renderRunners();renderResults();renderStats()}
function renderRunners(){let g=$("runnersGrid");g.classList.toggle("single",state.runners.length===1);g.innerHTML=state.runners.map(r=>{let a=rr(r.id),last=a.at(-1),isDone=done(r.id),next=Math.min(state.totalDistance,(a.length+1)*state.splitDistance),arrival=next>=state.totalDistance,main=last?(state.displayMode==="lap"?fmt(last.lapMs):state.displayMode==="cumulative"?fmt(last.cumulativeMs):`${fmt(last.lapMs)} · ${fmt(last.cumulativeMs)}`):"Prêt",sub=last?`${last.speed.toFixed(1)} km/h${last.deltaMs==null?"":` · ${signed(last.deltaMs)} vs précédent`}`:`Premier passage à ${next} m`;return `<div class="runnerCard"><span class="runnerName">${esc(r.name)}</span><span class="runnerMeta">${a.length}/${splits()} passages</span><span class="runnerMainMetric">${main}</span><span class="runnerSubMetric">${sub}</span><button class="splitBtn ${arrival&&!isDone?"arrival":""}" data-runner="${r.id}" ${isDone?"disabled":""}>${isDone?"COURSE TERMINÉE":arrival?`ARRIVÉE · ${next} m`:`INTERMÉDIAIRE · ${next} m`}</button></div>`}).join("");g.querySelectorAll("[data-runner]").forEach(x=>x.onclick=()=>record(x.dataset.runner))}
function renderResults(){let a=state.results.filter(x=>state.mode==="training"||x.race===state.activeRace);$("resultsEmpty").hidden=!!a.length;$("resultsTable").classList.toggle("hidden",!a.length);$("resultsBody").innerHTML=a.map(x=>`<tr><td><strong>${esc(x.runnerName)}</strong></td><td>${state.mode==="training"?"—":x.race}</td><td>${x.distance} m</td><td>${fmt(x.lapMs)}</td><td>${fmt(x.cumulativeMs)}</td><td>${x.speed.toFixed(1)} km/h</td><td class="${x.deltaMs<0?"deltaGood":x.deltaMs>0?"deltaBad":""}">${signed(x.deltaMs)}</td></tr>`).join("")}
function renderStats(){let h=state.runners.map(r=>{let a=rr(r.id);if(!a.length)return"";let laps=a.map(x=>x.lapMs),best=Math.min(...laps),worst=Math.max(...laps),last=a.at(-1);return `<div class="statCard"><h3>${esc(r.name)}</h3><div class="statRow"><span>Distance</span><strong>${last.distance} m</strong></div><div class="statRow"><span>Temps</span><strong>${fmt(last.cumulativeMs)}</strong></div><div class="statRow"><span>Vitesse moy.</span><strong>${spd(last.distance,last.cumulativeMs).toFixed(1)} km/h</strong></div><div class="statRow"><span>Meilleur tour</span><strong>${fmt(best)}</strong></div><div class="statRow"><span>Plus lent</span><strong>${fmt(worst)}</strong></div><div class="statRow"><span>Écart régularité</span><strong>${short(worst-best)}</strong></div></div>`}).join("");$("statsGrid").innerHTML=h}
function renderPerf(){$("perfRecap").innerHTML=`<span>${state.totalDistance} m</span><span>Inter. ${state.splitDistance} m</span>`;$("raceTabs").classList.toggle("hidden",state.mode==="training");document.querySelectorAll("[data-race]").forEach(x=>x.classList.toggle("active",+x.dataset.race===state.activeRace));renderTimer();renderRunners();renderResults();renderStats();$("teacherRevealBtn").classList.add("hidden");$("ccfScores").classList.add("hidden")}
function render(){$("setupPanel").classList.toggle("hidden",state.view!=="setup");$("performancePanel").classList.toggle("hidden",state.view!=="performance");state.view==="setup"?renderSetup():renderPerf()}
function resultText(){return state.runners.map(r=>{let all=state.results.filter(x=>x.runnerId===r.id);return `${r.name}\n`+all.map(x=>`${x.distance} m : tour ${fmt(x.lapMs)} · cumul ${fmt(x.cumulativeMs)} · ${x.speed.toFixed(1)} km/h · écart ${signed(x.deltaMs)}`).join("\n")}).join("\n\n")}
function buildSheet(){let date=new Date().toLocaleDateString("fr-FR");$("captureSheet").innerHTML=`<div class="captureTitle"><h2>Chrono EPS · ${state.totalDistance} m</h2><p>${date} · Intermédiaires tous les ${state.splitDistance} m</p></div>`+state.runners.map(r=>{let all=state.results.filter(x=>x.runnerId===r.id),laps=all.map(x=>x.lapMs),last=all.at(-1);if(!all.length)return"";return `<section class="captureRunner"><h3>${esc(r.name)}</h3><table class="captureTable"><thead><tr><th>Passage</th><th>Tour</th><th>Cumul</th><th>Vitesse</th><th>Écart</th></tr></thead><tbody>${all.map(x=>`<tr><td>${state.mode!=="training"?`800 n°${x.race} · `:""}${x.distance} m</td><td>${fmt(x.lapMs)}</td><td>${fmt(x.cumulativeMs)}</td><td>${x.speed.toFixed(1)} km/h</td><td>${signed(x.deltaMs)}</td></tr>`).join("")}</tbody></table><div class="captureSummary"><span>Temps ${fmt(last.cumulativeMs)}</span><span>Vitesse moy. ${spd(last.distance,last.cumulativeMs).toFixed(1)} km/h</span><span>Meilleur ${fmt(Math.min(...laps))}</span><span>Régularité ${short(Math.max(...laps)-Math.min(...laps))}</span></div></section>`}).join("");$("carnetDialog").close();$("sheetDialog").showModal()}
async function openCarnet(){let text=resultText();try{await navigator.clipboard.writeText(text);toast("Résultats copiés.")}catch{}window.location.href=CARNET_URL}
async function shareSheet(){let text=resultText();if(navigator.share){try{await navigator.share({title:"Chrono EPS",text});return}catch{}}try{await navigator.clipboard.writeText(text);toast("Résultats copiés.")}catch{toast("Fais une capture d’écran de la fiche.")}}
function recovery(){state.recoveryStartedAt=Date.now();save();updateRecovery()}function updateRecovery(){if(!state.recoveryStartedAt){$("recoveryDisplay").textContent="";return}let left=Math.max(0,720000-(Date.now()-state.recoveryStartedAt));$("recoveryDisplay").textContent=`Récupération : ${fmt(left)}`;clearTimeout(recoveryTimer);if(left)recoveryTimer=setTimeout(updateRecovery,500)}
function newSession(){if(!confirm("Créer une nouvelle séance et effacer les temps ?"))return;state=base();save();render()}
$("addRunnerBtn").onclick=addRunner;$("launchPerformanceBtn").onclick=launch;$("backSetupBtn").onclick=()=>{pause();state.view="setup";save();render()};$("startBtn").onclick=start;$("pauseBtn").onclick=pause;$("resetBtn").onclick=reset;$("undoBtn").onclick=()=>{let idx=[...state.results].map((x,i)=>({x,i})).filter(o=>o.x.race===state.activeRace).at(-1)?.i;if(idx==null)return toast("Rien à annuler.");state.results.splice(idx,1);save();renderPerf()};$("newSessionBtn").onclick=newSession;$("carnetBtn").onclick=()=>$("carnetDialog").showModal();$("openCarnetBtn").onclick=openCarnet;$("saveLaterBtn").onclick=buildSheet;$("closeSheetBtn").onclick=()=>$("sheetDialog").close();$("shareSheetBtn").onclick=shareSheet;$("startRecoveryBtn").onclick=recovery;document.querySelectorAll('[name="mode"]').forEach(x=>x.onchange=()=>{state.mode=x.value;if(state.mode!=="training"){state.totalDistance=800;state.splitDistance=200;state.displayMode="cumulative"}save();renderSetup()});["totalDistance","splitDistance","displayMode","targetTime","customDistance","customSplit"].forEach(id=>$(id).onchange=readConfig);$("totalDistance").onchange=()=>{$("customDistanceWrap").classList.toggle("hidden",$("totalDistance").value!=="custom");readConfig()};$("splitDistance").onchange=()=>{$("customSplitWrap").classList.toggle("hidden",$("splitDistance").value!=="custom");readConfig()};document.querySelectorAll("[data-race]").forEach(x=>x.onclick=()=>{pause();state.activeRace=+x.dataset.race;state.started=state.running=false;state.accumulatedMs=0;save();renderPerf()});window.addEventListener("online",()=>$("offlineBadge").textContent="En ligne");window.addEventListener("offline",()=>$("offlineBadge").textContent="Hors ligne prêt");if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");render();tick();updateRecovery();
})();